### ISSUE TITLE
Segfaulting when you don't have a proper API setup

### ISSUE THREAD

**Issue by ApprenticeofEnder** [LeeBrotherston/badflare#1]
Tested the app against my own domain, seems as though the Shodan API plan needs filters/paging to work properly. And if it doesn't have those, the app segfaults. Not a breaking issue, but it might help overall robustness. A mention in the README of the need for filters or paging (if it doesn't already exist) in the API plan would also help usability.

```
'<OBFUSCATED>' has IP(s) which are part of the Cloudflare network
Shodan Issue: Please upgrade your API plan to use filters or paging.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x637b4f]

goroutine 1 [running]:
main.main()
	/opt/badflare/main.go:108 +0x48f
```

**Comment by LeeBrotherston** [comment]
Thanks very much for the feedback, and apologies it took a little while.  But made a small change just now to more gracefully handle having a bad API key for shodan :)
